version: '3'

services:

  identity-db:
    container_name: object-identity-db
    image: mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=magcentre
    networks:
      - cloud-network
    volumes:
      - /home/prasanna/container-stroage/object-identity:/data/db
      
  mongo-express:
    container_name: object-identity-db-ui
    image: mongo-express
    stdin_open: true
    tty: true
    restart: unless-stopped
    environment:
        - ME_CONFIG_MONGODB_SERVER=object-identity-db
        - ME_CONFIG_MONGODB_PORT=27017
        - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    depends_on:
        - identity-db
    ports:
      - 8081:8081
    networks:
      - cloud-network

  service:
    container_name: object-identity-service
    depends_on:
      - identity-db
    build: .
    restart: unless-stopped
    ports:
      - 5004:5004
    stdin_open: true
    tty: true
    networks:
      - cloud-network

networks:
  cloud-network:
    name: cloud-network
