version: '3'

services:

  object-identity-db:
    container_name: object-identity-db
    image: mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=magcentre
    networks:
      - cloud-network

  object-identity:
    container_name: object-identity
    depends_on:
      - object-identity-db
    build: .
    restart: unless-stopped
    ports:
      - 5004:5004
    stdin_open: true
    tty: true
    networks:
      - cloud-network

networks:
  cloud-network:
    name: cloud-network
